(("package" . "orgtmpls4pdf")
 ("version" . "1.2.3")
 ("section" . "misc")
 ("priority" . "optional")
 ("maintainer" . "Xu Xin <sxuxin@protonmail.com>")
 ("description" . "Org templates for exporting to pdf")
 ("prefix" . "/usr")
 ("shebang" . "#! /usr/bin/chez --script")
 ("languages" . "zh_CN"))

