(("machine" . "ta6nt")
 ("scheme" . "9.5.8")
 ("format" . "exe")
 ("depends" . "")
 ("prefix" . "/InstallFiles")
 ("shebang" . "#! scheme --script")
 ("makensis" . "\"C:\\Program Files (X86)\\NSIS\\makensis.exe\"")
 )
